/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lchat;

import chatConnection.ConnectToServer;
import java.awt.TextArea;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author dgerontop
 */
public class LChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form LChatGUI
     */
    settingsGUI setupGui = new settingsGUI();
    ConnectToServer con = new ConnectToServer();
    InetAddress server;
    String svr = setupGui.getServer();

    public LChatGUI() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatPanel = new java.awt.Panel();
        userList = new java.awt.List();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        sendButton = new java.awt.Button();
        label2 = new java.awt.Label();
        chatArea = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitItem = new javax.swing.JMenuItem();
        Settings = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LChat");
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2);
        flowLayout1.setAlignOnBaseline(true);
        getContentPane().setLayout(flowLayout1);

        chatPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chatPanel.add(userList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 430));

        label1.setBackground(new java.awt.Color(102, 102, 102));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        label1.setText("Enter :");
        chatPanel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 80, 30));

        textField1.setBackground(new java.awt.Color(204, 204, 204));
        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        chatPanel.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 440, 30));

        sendButton.setBackground(new java.awt.Color(204, 204, 204));
        sendButton.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        sendButton.setLabel("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        chatPanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 440, 70, 30));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(204, 204, 204));
        label2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        label2.setText("Chat List");
        chatPanel.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        chatArea.setEditable(false);
        chatArea.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                chatAreaComponentShown(evt);
            }
        });
        chatPanel.add(chatArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 570, 390));

        getContentPane().add(chatPanel);

        jMenu1.setText("File");

        exitItem.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        Settings.setText("Edit");
        Settings.setAlignmentX(4.0F);
        Settings.setBorderPainted(true);

        jMenuItem1.setText("Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Settings.add(jMenuItem1);

        jMenuBar1.add(Settings);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//chatArea.append(con.receiveData());
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String msg = String.format("User : %s\n", textField1.getText());
        
        svr = setupGui.getServer();
        textField1.getAccessibleContext();
        //textArea1.setText(textField1.getText());
        con.sendData(svr, 28988, msg);
        chatArea.append(msg);
        textField1.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
        System.exit((0));
    }//GEN-LAST:event_exitItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        setupGui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void chatAreaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_chatAreaComponentShown
        // TODO add your handling code here:
        appendchat();
    }//GEN-LAST:event_chatAreaComponentShown

    public void appendchat() {
        
        
        chatArea.append(con.receiveData());
        System.out.println(con.receiveData() + "->Started");
        

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Settings;
    private java.awt.TextArea chatArea;
    ConnectToServer conn = new ConnectToServer();
    private java.awt.Panel chatPanel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Button sendButton;
    private java.awt.TextField textField1;
    private java.awt.List userList;
    // End of variables declaration//GEN-END:variables
}
